# --- Created by Slick DDL
# To stop Slick DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table `biography` (`ID` INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,`NAME` VARCHAR(254) NOT NULL,`BIO_TYPE` INTEGER NOT NULL,`IMAGE_PATH` VARCHAR(254) NOT NULL,`THUMB_PATH` VARCHAR(254) NOT NULL,`BIO_TEXT` VARCHAR(254) NOT NULL);
create table `discography` (`ID` INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,`NAME` VARCHAR(254) NOT NULL,`RELEASE_TYPE` INTEGER NOT NULL,`IMAGE` VARCHAR(254) NOT NULL);
create table `person` (`name` VARCHAR(254) NOT NULL PRIMARY KEY,`age` VARCHAR(254) NOT NULL);
create table `posts` (`ID` INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,`ITEM_TITLE` VARCHAR(254) NOT NULL,`TYPE` INTEGER NOT NULL,`DATE_CREATED` TIMESTAMP NOT NULL,`AUTHOR` VARCHAR(254) NOT NULL,`CONTENT` VARCHAR(254) NOT NULL,`EXTRA_DATA` VARCHAR(254) NOT NULL);
create table `tracks` (`ID` INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,`RELEASE_ID` INTEGER NOT NULL,`POSITION` INTEGER NOT NULL,`NAME` VARCHAR(254) NOT NULL);
create table `users` (`ID` INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,`EMAIL` VARCHAR(254) NOT NULL,`PASSWORD` VARCHAR(254) NOT NULL,`NAME` VARCHAR(254) NOT NULL,`ROLE` VARCHAR(254) NOT NULL);
alter table `tracks` add constraint `REL_FK` foreign key(`RELEASE_ID`) references `discography`(`ID`) on update NO ACTION on delete NO ACTION;

# --- !Downs

ALTER TABLE tracks DROP FOREIGN KEY REL_FK;
drop table `users`;
drop table `tracks`;
drop table `posts`;
drop table `person`;
drop table `discography`;
drop table `biography`;

