# --- Created by Slick DDL
# To stop Slick DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table "POSTTAGS" ("id" VARCHAR NOT NULL PRIMARY KEY,"title" VARCHAR NOT NULL);
create table "POST_TAGS" ("postId" VARCHAR NOT NULL,"tagId" VARCHAR NOT NULL);
create table "Profiles" ("ID" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"USER_ID" INTEGER NOT NULL,"ABOUT" VARCHAR NOT NULL,"AVATAR" VARCHAR NOT NULL);
create table "posts" ("ID" VARCHAR NOT NULL PRIMARY KEY,"ITEM_TITLE" VARCHAR NOT NULL,"TYPE" INTEGER NOT NULL,"DATE_CREATED" TIMESTAMP NOT NULL,"AUTHOR" VARCHAR NOT NULL,"CONTENT" TEXT NOT NULL,"EXTRA_DATA" VARCHAR NOT NULL,"DRAFT" BOOLEAN NOT NULL,"USER_ID" INTEGER);
create table "user_alias" ("ID" VARCHAR NOT NULL PRIMARY KEY,"USERID" INTEGER NOT NULL,"ALIAS" VARCHAR NOT NULL);
create table "users" ("ID" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"EMAIL" VARCHAR NOT NULL,"PASSWORD" VARCHAR NOT NULL,"NAME" VARCHAR NOT NULL,"ROLE" VARCHAR NOT NULL,"ALIAS_LIMIT" INTEGER);
alter table "POST_TAGS" add constraint "post_fk" foreign key("postId") references "posts"("ID") on update NO ACTION on delete NO ACTION;
alter table "POST_TAGS" add constraint "tag_fk" foreign key("tagId") references "POSTTAGS"("id") on update NO ACTION on delete NO ACTION;
alter table "Profiles" add constraint "USER_FK" foreign key("USER_ID") references "users"("ID") on update NO ACTION on delete NO ACTION;
alter table "user_alias" add constraint "ACCOUNT_FK" foreign key("USERID") references "users"("ID") on update NO ACTION on delete NO ACTION;

# --- !Downs

alter table "user_alias" drop constraint "ACCOUNT_FK";
alter table "Profiles" drop constraint "USER_FK";
alter table "POST_TAGS" drop constraint "post_fk";
alter table "POST_TAGS" drop constraint "tag_fk";
drop table "users";
drop table "user_alias";
drop table "posts";
drop table "Profiles";
drop table "POST_TAGS";
drop table "POSTTAGS";

