# --- Created by Slick DDL
# To stop Slick DDL generation, remove this comment and start using Evolutions

# --- !Ups

CREATE TABLE `POSTTAGS` (
  `id`    VARCHAR(254) NOT NULL PRIMARY KEY,
  `title` VARCHAR(254) NOT NULL
);
CREATE TABLE `POST_TAGS` (
  `postId` VARCHAR(254) NOT NULL,
  `tagId`  VARCHAR(254) NOT NULL
);
CREATE TABLE `Profiles` (
  `ID`      INTEGER      NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `USER_ID` INTEGER      NOT NULL,
  `ABOUT`   VARCHAR(254) NOT NULL,
  `AVATAR`  VARCHAR(254) NOT NULL
);
CREATE TABLE `posts` (
  `ID`           VARCHAR(254) NOT NULL PRIMARY KEY,
  `ITEM_TITLE`   VARCHAR(254) NOT NULL,
  `TYPE`         INTEGER      NOT NULL,
  `DATE_CREATED` TIMESTAMP    NOT NULL,
  `AUTHOR`       VARCHAR(254) NOT NULL,
  `CONTENT`      VARCHAR(254) NOT NULL,
  `EXTRA_DATA`   VARCHAR(254) NOT NULL,
  `DRAFT`        BOOLEAN      NOT NULL,
  `USER_ID`      INTEGER
);
CREATE TABLE `user_alias` (
  `ID`     VARCHAR(254) NOT NULL PRIMARY KEY,
  `USERID` INTEGER      NOT NULL,
  `ALIAS`  VARCHAR(254) NOT NULL
);
CREATE TABLE `users` (
  `ID`          INTEGER      NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `EMAIL`       VARCHAR(254) NOT NULL,
  `PASSWORD`    VARCHAR(254) NOT NULL,
  `NAME`        VARCHAR(254) NOT NULL,
  `ROLE`        VARCHAR(254) NOT NULL,
  `ALIAS_LIMIT` INTEGER
);
ALTER TABLE `POST_TAGS` ADD CONSTRAINT `post_fk` FOREIGN KEY (`postId`) REFERENCES `posts` (`ID`) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `POST_TAGS` ADD CONSTRAINT `tag_fk` FOREIGN KEY (`tagId`) REFERENCES `POSTTAGS` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `Profiles` ADD CONSTRAINT `USER_FK` FOREIGN KEY (`USER_ID`) REFERENCES `users` (`ID`) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `user_alias` ADD CONSTRAINT `ACCOUNT_FK` FOREIGN KEY (`USERID`) REFERENCES `users` (`ID`) ON UPDATE NO ACTION ON DELETE NO ACTION;

# --- !Downs

ALTER TABLE user_alias DROP FOREIGN KEY ACCOUNT_FK;
ALTER TABLE Profiles DROP FOREIGN KEY USER_FK;
ALTER TABLE POST_TAGS DROP FOREIGN KEY post_fk;
ALTER TABLE POST_TAGS DROP FOREIGN KEY tag_fk;
DROP TABLE `users`;
DROP TABLE `user_alias`;
DROP TABLE `posts`;
DROP TABLE `Profiles`;
DROP TABLE `POST_TAGS`;
DROP TABLE `POSTTAGS`;

